FROM debian:stable-slim
MAINTAINER sig-platform@spinnaker.io

WORKDIR /opt/deck
COPY docker        /opt/deck/docker
RUN docker/setup-apache2.sh

COPY build/webpack /opt/deck/html
RUN chown -R www-data:www-data /opt/deck
USER www-data

ENTRYPOINT ["/opt/deck/docker/run-apache2.sh"]
